spring.application.name=agribuy

spring.datasource.url=jdbc:mysql://localhost:3306/agribuy
spring.datasource.username=root
spring.datasource.password=Likhith@321

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
